apiVersion: 1

contactPoints:
  - orgId: 1
    name: ntfy-grafana-alerts
    receivers:
      - uid: ntfy-grafana-alerts-webhook
        type: webhook
        settings:
          url: http://ntfy:80/grafana-alerts
          httpMethod: POST
          maxAlerts: "10"

policies:
  - orgId: 1
    receiver: ntfy-grafana-alerts
    group_by:
      - grafana_folder
      - alertname
      - service
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h

