apiVersion: 1

datasources:
  - name: prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST

  - name: grafana-postgresql-datasource
    type: postgres
    uid: ffq7bvja2gsu8d
    typeName: PostgreSQL
    access: proxy
    url: postgres-metrics-db:5432
    user: postgres
    isDefault: false
    editable: true
    jsonData:
      connMaxLifetime: 14400
      database: metrics_db
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      sslmode: disable
    secureJsonData:
      password: postgres
