apiVersion: 1

datasources:
  - name: prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      alertmanagerUid: efr3nt8rv9y4gf
      alerting: true

  - name: grafana-postgresql-datasource
    type: postgres
    uid: ffq7bvja2gsu8d
    typeName: PostgreSQL
    access: proxy
    url: postgres-metrics-db:5432
    user: postgres
    isDefault: false
    editable: true
    jsonData:
      connMaxLifetime: 14400
      database: metrics_db
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      sslmode: disable
    secureJsonData:
      password: postgres

  - name: infinity-json-placeholder
    type: yesoreyeram-infinity-datasource
    uid: infinity-json-placeholder
    typeName: "Infinity"
    access: proxy
    url: "https://jsonplaceholder.typicode.com"
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      global_queries: []
      pdcInjected: false
    secureJsonData:
      password: ""

  - name: infinity-csv-script-live-metric
    type: yesoreyeram-infinity-datasource
    uid: infinity-csv-script-live-metric
    typeName: "Infinity"
    access: proxy
    url: "http://grafana:3000/public/testdata/live_metric.csv"
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      global_queries: []
      pdcInjected: false
    secureJsonData:
      password: ""

  - name: testdata-datasource
    type: testdata
    access: proxy
    isDefault: false

  - name: prometheus-alertmanager-datasource
    type: alertmanager
    uid: efr3nt8rv9y4gf
    typeName: Alertmanager
    access: proxy
    url: "http://alertmanager:9093"
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      handleGrafanaManagedAlerts: true
      implementation: "prometheus"
      pdcInjected: false
      alerting: true